name: gpa_and_cgpa_calculator
description: GPA & CGPA Calculator (Flutter)
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_mobile_ads: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  connectivity_plus: ^3.0.3
  shared_preferences: ^2.1.1
  pdf: ^3.8.1
  unity_ads_plugin: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
